apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 3  # Adjust the replica count as needed
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgre-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: dan
        - name: POSTGRES_DB
          value: Uni_SQL
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: init-sql
        configMap:
          name: init-sql
          items:
          - key: init.sql
            path: init.sql